# Generated by Django 2.1.4 on 2018-12-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discgolf_api', '0002_course_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hole',
            old_name='distance',
            new_name='par',
        ),
        migrations.AddField(
            model_name='hole',
            name='course_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
